version: "3.7"
services:
    # Nginx
    nginx:
        image: nginx:latest
        container_name: '${APP_NAME:-laravel}-nginx'
        restart: unless-stopped
        ports:
            - '${FORWARD_NGINX_PORT:-8081}:80'
        environment:
            NGINX_PORT: '${APP_PORT:-80}'
            NGINX_HOST: '${APP_DOMAIN:-localhost}'
        volumes:
            - './:/var/www'
            - './docker/prod/nginx/templates:/etc/nginx/templates'
            - './docker/prod/nginx/nginx.conf:/etc/nginx/nginx.conf'
        depends_on:
            - php-fpm
        networks:
            - laravel

    # Php-fpm
    php-fpm:
        build:
            args:
                phpversion: '${PHP_VERSION:-8.2.0}'
            context: 'docker/prod/php-fpm'
            dockerfile: Dockerfile
        container_name: '${APP_NAME:-laravel}-php-fpm'
        working_dir: '/var/www'
        volumes:
            - './:/var/www'
            - './docker/prod/php-fpm/php.ini:/usr/local/etc/php/php.ini'
        networks:
            - laravel

    # Postgresql
    pgsql:
        image: postgres:15
        container_name: '${APP_NAME:-laravel}-pgsql'
        restart: unless-stopped
        environment:
            PGPASSWORD: '${DB_PASSWORD:-root}'
            POSTGRES_DB: '${DB_DATABASE:-laravel}'
            POSTGRES_USER: '${DB_USERNAME:-root}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-root}'
        ports:
            #      - '${FORWARD_DB_PORT:-5432}:5432'
            - '5432'
        volumes:
            - './docker/prod/postgres/initdb.d:/docker-entrypoint-initdb.d'
            - '~/Databases/postgresql/${APP_NAME:-laravel}:/var/lib/postgresql/data'
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_USERNAME:-root}", "-U", "${DB_USERNAME:-root}"]
            retries: 3
            timeout: 5s

    # Redis
    redis:
        image: redis:alpine
        container_name: '${APP_NAME:-laravel}-redis'
        ports:
            #      - '${FORWARD_REDIS_PORT:-6379}:6379'
            - '6379'
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    # Node
    node:
        image: node:18-alpine
        command: sh -c 'npm install -g npm@9.8.1 && npm install && npm run start'
        container_name: '${APP_NAME:-laravel}-node'
        ports:
            - "3000:3000"
        working_dir: '/var/www'
        volumes:
            - './:/var/www'
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
